### ISSUE TITLE
增加即时通讯服务的检查项

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/leancloud-status#3]
## 问题

目前只有一个 session/open 的检查，感觉有点少

## 期望

增加更多检查项：

* 创建/查询会话
* 成员加入/离开会话
* 发送/接收消息
* RTM REST API 的测试
* ...

**Comment by leeyeh** [comment]
检查的项越多，误报的可能就越大，尤其时这种本来设计中就可能会出现延迟的异步操作。

**Comment by zapcannon87** [comment]
误报不是不增加检查项的理由吧。另外，我认为「误报」即表示程序有 bug，有助于我们改善问题。

**Comment by jysperm** [comment]
建议在内部监控系统加，状态页是为了对外提供信息，不是对内的监控。
